#!/bin/bash
set +x
						cd c_programs
						echo -e "\n\n**************************** This is a Build JOB **************************** "

						if [[ -x "ABC.exe" ]]; then
							echo "STEP 1:	Cleaning existing builds ........"
								ls *.exe | nl | sed 's/	/) /g' | tr '\n' ' ' 
									rm -f "./ABC.exe" 
							echo -e "\n\nSTEP 2:	Cleaning existing Object files........"
								ls *.o | nl | sed 's/	/) /g' | tr '\n' ' '
									rm -f *.o
						fi   
							echo -e "\n\nSTEP 3:	Initiating Build for below files (using make)........"
								ls *.c | nl | sed 's/	/) /g' | tr '\n' ' '
							echo -e "\n"    
								make

						#dt=$(date +%Y-%m-%d_%H:%M:%S)

						if [[ -x "./ABC.exe" ]]; then  
							echo -e "\nSTEP 4:	Build Successful"
							echo "       	BUILD_FILE: $(pwd)/ABC.exe"
							[[ -d '/opt/jenkins/workspace/Build' ]] || mkdir --parents '/opt/jenkins/workspace/Build'
							cd /opt/jenkins/workspace/Build/
							[[ -d "/opt/jenkins/workspace/Build/artifactory" ]] && rm -rf /opt/jenkins/workspace/Build/artifactory 
							git clone git@github.com:Anirudh48/artifactory.git
							cd artifactory
							file=$(ls ABC_* | sort -n | tail -1)
							if [[ -n "$file" ]]; then
								filename="${file%.*}"
								old_version=$(echo $filename | awk -F 'v' '{print $2}')
								new_version=$(echo "$old_version + 0.1" | bc)
							else 
								file='NA'; old_version='0.0'; new_version='1.0'
							fi    
							echo -e "\nLAST_BUILD: $file \nOLD_BUILD_VERSION: $old_version \nNEW_BUILD_VERSION: $new_version"
							
							cp "/opt/jenkins/workspace/Build/c_programs/ABC.exe" "/opt/jenkins/workspace/Build/artifactory/ABC_v${new_version}.exe"
							
							git config --global push.default simple
							git config --global user.name "Jenkins"
							git config --global user.email master.jenkins@build.com
							git status
							git add --all && git commit -m "Build ABC_${dt}.exe"
							git push origin master
							echo -e "\nSTEP 3:	Build pushed to artifactory"
								
						else
							echo -e "**************** ERROR *********************\n"
							echo "Build failure - No executable file generated"
							echo -e "********************************************\n"
							exit 1
						fi    

						echo -e "\n************************************************************************** "
